// Generated by CoffeeScript 2.7.0
  // jstester.test.coffee
import {
  undef
} from '@jdeighan/base-utils';

import {
  jstester
} from '@jdeighan/unit-tester';

// ---------------------------------------------------------------------------
jstester.equal(8, `let x = 42;`, `let x = 42;`);

jstester.equal(14, `let x = 42;`, `let
x
=
42
;`);

// --- Things we want to ignore:
//        1. The line number something is on
//        2. missing semicolons
//        3. trailing commas
//        4. the type of quote mark used for strings
//        5. extra parentheses
//        6. indent level
jstester.equal(32, `let x = 42;
if ((x == 42)) {
	console.log('this', undef);
	}`, `let x = 42
	if (x == 42) {
		console.log(
			"this",
			undef,
			);
		}`);

jstester.equal(47, `let x = 42;
if ((x == 42)) {
	console.log('this', undef);
	}`, `let x=42;if(x==42){console.log("this",undef);}`);
