// Generated by CoffeeScript 2.7.0
// JSTester.coffee
import test from 'ava';

import prettier from 'prettier';

import {
  undef,
  defined,
  notdefined,
  DUMP
} from '@jdeighan/base-utils';

import {
  assert
} from '@jdeighan/base-utils/exceptions';

import {
  getTestName
} from '@jdeighan/unit-tester/utils';

// ---------------------------------------------------------------------------
export var JSTester = class JSTester {
  transformValue(input) {
    return input;
  }

  // ........................................................................
  transformExpected(input) {
    return input;
  }

  // ........................................................................
  normalize(js) {
    var err, result;
    try {
      result = prettier.format(js, {
        parser: 'flow'
      });
      return result;
    } catch (error) {
      err = error;
      console.log("prettier failed");
      DUMP('JavaScript', js);
      throw err;
    }
  }

  // ........................................................................
  equal(lineNum, js1, js2) {
    var err, norm1, norm2;
    js1 = this.transformValue(js1);
    js2 = this.transformExpected(js2);
    try {
      // --- normalize js1
      norm1 = this.normalize(js1);
    } catch (error) {
      err = error;
      DUMP('JavaScript 1', js1);
      console.log(`ERROR in JSTester 1: ${err.message}`);
      throw err;
    }
    try {
      // --- normalize js2
      norm2 = this.normalize(js2);
    } catch (error) {
      err = error;
      DUMP('JavaScript 2', js2);
      console.log(`ERROR in JSTester 2: ${err.message}`);
      throw err;
    }
    test(getTestName(lineNum), function(t) {
      return t.is(norm1, norm2);
    });
  }

};

// ---------------------------------------------------------------------------
export var jstester = new JSTester();
