// Generated by CoffeeScript 2.7.0
  // utils.coffee
import {
  toArray,
  nonEmpty
} from '@jdeighan/base-utils';

// ---------------------------------------------------------------------------
export var normalize = function(block) {
  var i, lLines, len, line, ref;
  if (typeof block !== 'string') {
    return block;
  }
  // --- Remove blank lines
  //     In remaining lines:
  //        - Remove leading and trailing whitespace
  //        - Convert all whitespace to single space character
  lLines = [];
  ref = toArray(block);
  for (i = 0, len = ref.length; i < len; i++) {
    line = ref[i];
    line = line.trim(); // remove leading/trailing whitespace
    if (nonEmpty(line)) {
      lLines.push(line.replace(/\s+/g, ' '));
    }
  }
  return lLines.join('\n');
};

// ---------------------------------------------------------------------------
export var super_normalize = function(block) {
  var func;
  if (typeof block !== 'string') {
    return block;
  }
  // --- Collapse ALL whitespace, including newlines, to space char
  //     Remove whitespace around =+*()<>[]
  block = block.replace(/\s+/sg, ' ');
  func = (match, ch) => {
    return ch;
  };
  block = block.replace(/\s*([=+*()<>\[\]])\s*/g, func);
  return block;
};
